/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sys_android_util_JNIMp3Encode */

#ifndef _Included_com_sys_android_util_JNIMp3Encode
#define _Included_com_sys_android_util_JNIMp3Encode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sys_android_util_JNIMp3Encode
 * Method:    convertmp3
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_sys_android_util_JNIMp3Encode_convertmp3
  (JNIEnv *, jclass, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
